export enum ErrorCode {
  LESS_TOKEN = 'LESS_TOKEN',
  CELL_SMALL = 'CELL_SMALL',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  TOKEN_SELF = 'TOKEN_SELF',
  EMAIL_NOT_SEND = 'EMAIL_NOT_SEND',
  TIME_IN = 'TIME_IN',
  MEME_COIN_ENOUGH = 'MEME_COIN_ENOUGH',
  MINE_FAIL = 'MINE_FAIL',
  MINE_END = 'MINE_END'
}
