export enum NotifyType {

  DNA = 'DNA',
  CELL = 'CELL',
  TOKEN = 'TOKEN',
  ADMIN = 'ADMIN',
  CREATING = 'CREATING',
  ALLOWANCE = 'ALLOWANCE',
  MEME_COIN = 'MEME_COIN',
  BATTLE_REQUEST = 'BATTLE_REQUEST',
  BATTLE_RESPONSE = 'BATTLE_RESPONSE',
  BATTLE_COMPLETE = 'BATTLE_COMPLETE'
}
